language: julia
os:
    - osx
    - linux
julia:
    - 1.3.1
    - 1
    - nightly
notifications:
    email: false
jobs:
  include:
    - stage: "Documentation"
      julia: 1.4.2
      os: linux
      script:
        - julia --project=docs -e 'using Pkg; Pkg.add(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs docs/make.jl
      after_success: skip
after_success:
    - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
